site_name: Chaudiere
theme: readthedocs
repo_url: https://github.com/example/repository/
docs_dir: docs/ 
nav:
    - Home: index.md
    - Raspbian Install: raspbian_install.md
    - Chaudiere Install: chaudiere_install.md
    - Software: software.md

